version: '3'
services:
  node64:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.66
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 64 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"


  node65:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.67
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 65 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node66:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.68
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 66 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node67:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.69
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 67 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node68:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.70
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 68"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"
  node69:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.71
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 69"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"
  node70:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.72
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 70"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"
  node71:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.73
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 71"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node72:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.74
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 72"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node73:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.75
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 73"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node74:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.76
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 74"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node75:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.77
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 75"
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"


  node76:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.78
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 76 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"


  node77:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.79
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 77 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node78:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.80
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 78 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

  node79:
    image: dagbrb:test
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/hosts:/app/hosts
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/status:/app/status
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/RBC.py:/app/RBC.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/DAGBRB.py:/app/DAGBRB.py
      - /home/molly/Desktop/DAGBRB/DAG/DAG_BRB/network.py:/app/network.py
    networks:
      my-overlay-network:
        ipv4_address: 172.50.0.81
    command: sh -c "tc qdisc add dev eth0 root netem delay 10ms && python network.py -s hosts -a 2 -i 79 "
    privileged: true
    labels:
      - "org.label-schema.tc.enabled=1"
      - "org.label-schema.tc.rate=1000mbps"
      - "org.label-schema.tc.ceil=1000mbps"

# 添加更多的容器定义，每个容器使用类似的格式
# ...

networks:
  my-overlay-network:
    external: true